### ISSUE TITLE
Program 2:

### ISSUE THREAD

**Issue by riyazahamedn24** [hari-eur/Nithya-B---Riyaz#1]
Solve the below problem:

Write a C program that reads in a string as input from us and to print the longest palindrome that can be formed from the characters in the string.

Note:

-  _A palindrome is a word, phrase, number, or other sequence of characters that reads the same forward and backward (ignoring spaces, punctuation, and capitalization)._
- **If there are multiple palindromes of the same length, your program should print out the one that comes first alphabetically.**

For example, if you enter the string "I have reached final level in racecar game".
 your program should output "racecar".

**Comment by nithyabalagopal23** [comment]
#include <stdio.h>
#include <string.h>


void printSubStr(char* str, int low, int high)
{
	for (int i = low; i <= high; ++i)
		printf("%c", str[i]);
}


int longestPalSubstr(char* str)
{
	int n = strlen(str); 
	if (n < 2) 
		return n; 

	int maxLength = 1, start = 0;
	int low, high;
	for (int i = 0; i < n; i++) {
		low = i - 1;
		high = i + 1;
		while (high < n
			&& str[high] == str[i]) 
			high++;

		while (low >= 0
			&& str[low] == str[i]) 
			low--;

		while (low >= 0 && high < n
			&& str[low] == str[high]) {
			low--; 
			high++; 
		}

		int length = high - low - 1;
		if (maxLength < length) {
			maxLength = length;
			start = low + 1;
		}
	}
	printf("Longest palindrome substring is: ");
	printSubStr(str, start, start + maxLength - 1);
	return maxLength;
}


int main()
{
	char str[100];
	scanf("%[^\n]%*c", str);

	printf("\nLength is: %d", longestPalSubstr(str));
	return 0;
}

since i was not able to solve on my own, I went through different sources to learn the approach. here i have used pointers to expand from the center and checked if the left pointer = right pointer and return the maximum length.

**Comment by riyazahamedn24** [comment]
@nithyabalagopal23, Good that you found a solution.
You did all the 3 Assigned tasks really well. Also, there are few things to be improved. I will try to upload a c-programming document for more understanding.

**Comment by nithyabalagopal23** [comment]
Thankyou sir, I'll go through the document and learn more about it.
